name: Contributor List
on:
  push:
    branches:
      - master
jobs:
  contributor_list:
    name: Contributor List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rafaelcenzano/contributor_list@master
        with:
          commit_message: 📝 Update contributors list
